Fix Error while storing uploaded file #370
Uploading a file using the geoserver api returns Caused by:
java.lang.IllegalStateException: Could not create file.

georchestra 25 introduce sandboxing by default:
https://docs.geoserver.org/stable/en/user/security/sandbox.html
Consequently, the variable GEOSERVER_FILESYSTEM_SANDBOX should be set.